### ISSUE TITLE
Unable to run objective test

### ISSUE THREAD

**Issue by gautamtaneja** [nityansuman/automated-test-app#16]
local variable 'tags' referenced before assignment
![image](https://user-images.githubusercontent.com/72023081/143529466-60280ced-7687-4588-94cf-7d499217af72.png)

**Comment by nityansuman** [comment]
@gautamtaneja I think you have some installation issues with `nltk`. Looks like your pos tagging is failing.
The tags are created here: https://github.com/nityansuman/marvin/blob/main/src/objective.py#L101 and then being used.

**Comment by gautamtaneja** [comment]
Thanks for response, I found your project very helpful

**Comment by 4tstar** [comment]
I have the same issue, how to fix it ?
