### ISSUE TITLE
Article() not defined

### ISSUE THREAD

**Issue by TheBengineer** [nityansuman/automated-test-app#3]
Hello good sir! 

I keep getting an error on line 78 of atp/util.py:
`obj_a = Article(filename)`

That Article is not defined. I've been looking through your code to see if there was a missing import, but I can't find where it's supposed it be defined. I have all the requirements met, and NLTK downloaded.

Am I doing something silly here? 

Thanks,

~Ben

**Comment by WildDoogyPlumb** [comment]
I have found the fix. Change the line to:

obj_a = ObjectiveQuestion(filename)

**Comment by SHADOW13325** [comment]
@TheBengineer Didn't you got the .csv file not found error?? I am getting that

**Comment by nityansuman** [comment]
Issue resolved. Check for latest updates. @TheBengineer
